spring:
  mvc:
    view:
      prefix: WEB-INF/views/
      suffix: .jsp
  datasource:
    url: "jdbc:mariadb://localhost:3306/miniProj-db"
    username: "bituser"
    password: "1004"
    driver-class-name: org.mariadb.jdbc.Driver
#
#mybatis:
#  config-location: classpath:mybatis-config.xml  # MyBatis ?? ?? ??
#  mapper-locations: classpath:mapper/**/*.xml  # Mapper ?? ??

#server:
#  servlet:
#    jsp:
#      init-parameters: #?? jsp???? ??? ?? ??? ?
#        development: true
##  port: 8081
#
#logging:
#  level:
#    org:
#      mybatis: DEBUG